### ISSUE TITLE
画面遷移・TableViewCellについて

### ISSUE THREAD

**Issue by s11y** [nanoma/cafeapp#1]
@IBAction func savePage() の中の最後の行に
self.performSegueWithIdentifier("セグエの名前", sender: nil)
を書いて画面遷移させましょう

ListTableViewControllerのなかに、以下のように書きましょう
override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
}
この中にコードがcellをタップしたときに、実行されます
なので、この中に先ほどのself.performSegue~~を書いてあげてください

あとは、同じくListTableViewControllerの中に、
override perpareForSegueでindexPath.rowを次の画面に渡してあげてください

**Comment by nanoma** [comment]
ありがとうございます！
今コード上でセグエをつないでみたのですが、起動すると落ちてしまいます。reasonが見当たらないので、一度みていただけたら助かります。よろしくお願いします。

**Comment by s11y** [comment]
UIImageはNSUserDefaultsでは保存できないので、NSDataに変換してください。
変換の仕方は、ググッてもらって、1時間試して無理ならまた質問してください。

**Comment by nanoma** [comment]
おはようございます。NSDataに変換したのですが、エラーを吐いてしまいます。

**Comment by s11y** [comment]
BASE64のStringに変換する必要はないと思うよ
UIImagePNGRepresentationで変換したら、そのまま変換したものをNSUserDefaultsで保存して大丈夫です

**Comment by nanoma** [comment]
ありがとうございます！
